services:
  flask_app:
    container_name: flask_app
    image: mataneden/flask_phonebook_0.0.1
    build: .
    ports:
      - "4000:4000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
